Shopping Cart application
RedHatTraining/DO400-apps pull request #4
Opened 2020-10-14 16:10 UTC by psolarvi

2020-10-15 09:02 UTC, jramcast requested changes
Pretty complete app to show how integration testing works :)

I left some comments. Many of them are just suggestions we can discuss.

Also, this looks like the final solution, so instead of merging into `master`, we should merge this  pr to the `solutions` branch

2020-10-15 09:02 UTC, jramcast commented on shopping-cart/src/test/java/com/redhat/shopping/integration/white/box/ShoppingCartTest.java
> +        assertEquals(initialQty + incrementalQty, this.cartService.totalItems());
The assert is clearer by if we just hardcode the expected value:

```suggestion
        assertEquals(110, this.cartService.totalItems());
```

2020-10-15 09:02 UTC, jramcast commented on shopping-cart/src/test/java/com/redhat/shopping/integration/white/box/ShoppingCartTest.java
> +        this.cartService.addProduct(existingProductId, incrementalQty);
I would also say that the test setup is clearer if we just hardcode the parameter values in the `addProduct` calls

2020-10-15 09:27 UTC, psolarvi commented on shopping-cart/src/main/java/com/redhat/shopping/cart/AddToCartCommand.java
> +    }
That constructor is required by quarkus/java in order to do some magic and transform the request JSON body into an object.

2020-10-15 09:30 UTC, psolarvi commented on shopping-cart/src/main/java/com/redhat/shopping/cart/CartView.java
> +    }
Is the same reason, quarkus/java forced me to add that constructor. Without it, the app explodes when I try to return a view of the cart. :confused:

2020-10-19 13:05 UTC, jramcast approved these changes

2020-10-19 13:18 UTC, merged